---
- name: Instalar y configurar Web para NFTables
  hosts: [sec]
  become: yes
  vars:
    git_repo_url: "https://github.com/mpiasix2/nftablesweb.git"
    git_repo_path: "/var/www/nftablesweb"
  tasks:
  
  - name: Crear directorio /var/www
    file:
      path: /var/www
      state: directory
      mode: '0755'
       
  - name: Crear directorio /var/www/nftablesweb
    file:
      path: /var/www/nftablesweb
      state: directory
      mode: '0755'
  
  - name: Comprobar si existe el repositorio de nftablesweb
    stat:
      path: "{{ git_repo_path }}"
    register: repo_status

  - name: Preguntar si se desea sobrescribir el repositorio existente
    pause:
      prompt: "El repositorio ya existe. ¿Desea sobrescribirlo? (S/N)"
    when: repo_status.stat.exists

  - name: Clonar el repositorio de nftablesweb
    git:
      repo: "{{ git_repo_url }}"
      dest: "{{ git_repo_path }}"
    when: repo_status.stat.exists == False or pause.stdout == "S\n"
      
  - name: Crear ambiente virtual
    command: "py -3 -m venv .venv"
    args:
      chdir: "{{ git_repo_path }}"
      
  - name: Activar ambiente virtual
    command: ".venv/scripts/activate"
    args:
      chdir: "{{ git_repo_path }}"
    shell: yes

  - name: Instalar Flask
    command: "py -m pip install flask"
    args:
      chdir: "{{ git_repo_path }}"
      
  - name: Instalar MySQL Connector
    command: "py -m pip install mysql-connector-python"
    args:
      chdir: "{{ git_repo_path }}"
