- hosts: sec
  vars:
    git_repo_url: "https://github.com/mpiasix2/nftablesweb.git"
    git_repo_path: "/var/www/nftablesweb"
  tasks:
  - name: Comprobar si existe el repositorio de nftablesweb
    stat:
      path: "{{ git_repo_path }}"
    register: repo_status

  - name: Preguntar si se desea sobrescribir el repositorio existente
    pause:
      prompt: "El repositorio ya existe. ¿Desea sobrescribirlo? (S/N)"
    when: repo_status.stat.exists

  - name: Clonar el repositorio de nftablesweb
    git:
      repo: "{{ git_repo_url }}"
      dest: "{{ git_repo_path }}"
    when: repo_status.stat.exists == False or pause.stdout == "S\n"
