---
- name: Instalar y configurar SIEM
  hosts: [sec]
  become: yes
  tasks:

  - name: Instalando docker...
    become: true
    apt:
      name: docker.io
      state: present

  - name: Desplegando web...
    become: true
    shell: sudo docker run --rm -p 5000:80 mpisec/nft
