---
- name: Instalar y configurar web Nftables
  hosts: [sec]
  become: yes
  tasks:

  - name: Instalando docker...
    become: true
    apt:
      name: docker.io
      state: present
      
  - name: Instalando docker-py...
      become: true
      pip:
        name: docker-py

  - name: Desplegando web...
    become: true
    shell: sudo docker run --rm -p 5000:80 mpisec/nft
